import Primes

--Triangle, pentagonal, and hexagonal numbers are generated by 
-- the following formulae:
--        Triangle   T_(n)=n(n+1)/2   1, 3, 6, 10, 15, ...
--        Pentagonal   P_(n)=n(3n−1)/2   1, 5, 12, 22, 35, ...
--        Hexagonal   H_(n)=n(2n−1)   1, 6, 15, 28, 45, ...

-- It can be verified that T_(285) = P_(165) = H_(143) = 40755.

-- Find the next triangle number that is also pentagonal and hexagonal.

isPent :: Integer -> Bool
isPent n = (af == 0) && ai `mod` 6 == 5
    where (ai,af) = properFraction . sqrt $ 24 * (fromInteger n) + 1

ans = take 1 [x | x <- dropWhile (<= 40755) hexagonalNumbers, isPentagonalNumber x]

ansAlt = head [x | x <- scanl (+) 1 [5,9..], x > 40755, isPent x]

